language: cpp python

python: '2.7'

compiler:  
  - gcc
  
addons:
    apt:
        sources:
            - llvm-toolchain-precise
            - ubuntu-toolchain-r-test
        packages:
            - g++-5
    
install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cd ./3rdparty; wget --no-check-certificate http://cmake.org/files/v3.1/cmake-3.1.3-Linux-x86_64.tar.gz; tar -xzf cmake-3.1.3-Linux-x86_64.tar.gz; cd ..; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CXX="g++-5" CC="gcc-5"; fi      
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export PATH=$PWD/3rdparty/cmake-3.1.3-Linux-x86_64/bin:$PATH; fi
    - sudo apt-get install -y build-essential
    - sudo apt-get install -y cmake git libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev
    - sudo apt-get install -y python-dev python-numpy libtbb2 libtbb-dev libjpeg-dev libpng-dev libtiff-dev libjasper-dev libdc1394-22-dev
    - curl -sL https://github.com/opencv/opencv/archive/master.zip > opencv.zip
    - unzip opencv.zip
    - cd opencv-master

    - mkdir build
    - cd build

    - cmake -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=/usr/local ..
    - make -j7
    - sudo make install
    - sudo sh -c 'echo "/usr/local/lib" > /etc/ld.so.conf.d/opencv.conf'
    - sudo ldconfig
    - echo "OpenCV installed."
    - cd ../../

before_script:  
  - files=`find . -path ./3rdparty -o -prune ./opencv-master -prune -name \*.hpp -print -o -name \*.h -print -o -name \*.cpp -print -o -name \*.c -print | sed -e ':a;N;$!ba;s/\n/ /g'`
  - python ./3rdparty/utils/cpplint.py $files

script:   
  - mkdir build
  - cd build
  - cmake ..
  - make

after_success:
   - find . -executable -type f -print | while read app; do printf "\n=========================================\nExecutable:\t$app\n=========================================\n"; "$app"; done
